version: "3.4"
services:
  consul:
    image: consul:1.0.7
    command: consul agent -server -dev -client=0.0.0.0 -ui -bootstrap -log-level warn
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  reverse-proxy:
    image: traefik:1.6
    command: '--web --consulcatalog.endpoint=consul:8500 --consulcatalog.exposedbydefault=true --consulcatalog.domain=lb.local'
    ports:
      - "8080:8080"
      - "80:80"
    depends_on:
      - consul
    links:
      - consul

  registrator:
    depends_on:
      - consul
    image: marcuslinke/registrator:2017-10-25
    command: '-internal -cleanup=true -ttl=120 -ttl-refresh=55 -resync=30 consul://consul:8500'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    links:
      - consul

  web-server:
    image: crccheck/hello-world
    ports:
      - "8000:8000"
    environment:
      - SERVICE_8000_NAME=tester8000
